options:
  install_sources:
    type: string
    default: deb http://packages.elastic.co/beats/apt stable main
    description: apt repository to fetch beats from
  install_keys:
    type: string
    default: D88E42B4
    description: repository key
  device:
    type: string
    default: any
    description: |
      Device to listen on, eg eth0 is typically 0. See readme for more details.
  protocols:
    type: string
    description: |
      the ports on which Packetbeat can find each protocol. space
      separated protocol:port format.
    default: "http:80 http:8080 dns:53 mysql:3306 pgsql:5432 redis:6379 thrift:9090 mongodb:27017 memcached:11211"
